### ISSUE TITLE
Translations not running

### ISSUE THREAD

**Issue by kermie** [OXID-eSales/ddoe-wysiwyg-editor-module#4]
When running OXID eShop V6 in English, and activating the ddoe-wysiwyg-editor-module, the translations seem to be not correct although in the lang files, it seems to be okay: https://github.com/OXID-eSales/ddoe-wysiwyg-editor-module/blob/master/application/views/admin/en/ddoewysiwyg_lang.php

The view still comes up with DD_MEDIA_DIALOG, DD_CANCEL and "Suche" instead of "Search".

**Comment by pnkz** [comment]
Fixed in latest master branch.
