### ISSUE TITLE
kind of filemanger for better image organizing 

### ISSUE THREAD

**Issue by kaluzki** [OXID-eSales/ddoe-wysiwyg-editor-module#6]
It would be nice to have a filemanger, like wysiwygpro did:

![image](https://user-images.githubusercontent.com/1521167/33168191-632d3004-d040-11e7-81a2-5b0f0bc0bd67.png)

**Comment by Sieg** [comment]
Hello @kaluzki, i have moved your issue to our Bugtrack system. Please follow the progress in there: https://bugs.oxid-esales.com/view.php?id=6870
