### ISSUE TITLE
Editor corrupts `>` used in smarty variables

### ISSUE THREAD

**Issue by Crease29** [OXID-eSales/ddoe-wysiwyg-editor-module#9]
There is a problem in the latest version of the editor which causes object operators to be encoded to html entities.

Example from cms page "oxstartwelcome":
```
[{$oxcmp_user->oxuser__oxfname->value}] [{$oxcmp_user->oxuser__oxlname->value}]
```
becomes
```
[{$oxcmp_user-&gt;oxuser__oxfname-&gt;value}] [{$oxcmp_user-&gt;oxuser__oxlname-&gt;value}]
```

That causes an error on the page.

**Comment by Sieg** [comment]
Hi @Crease29, thanks for reporting the issue. As i see, its the same as reported in bugtrack and already fixed in latest version: https://bugs.oxid-esales.com/view.php?id=6514
